import * as posh from "./posh.js";
import * as zeroFir from "./zeroFir.js";
import * as pwdva from "./pwdva.js";
import * as dowry from "./dowry.js";

const templates = Object.fromEntries([posh, zeroFir, pwdva, dowry].map((t) => [t.type, t]));

export const DRAFT_TYPES = Object.keys(templates);

const DISCLAIMER = [
  "",
  "---",
  "This draft was generated by AROGYINI as a starting point. It is not legal advice.",
  "Have it checked by a lawyer before filing. Free legal aid is available from NALSA on 15100.",
].join("\n");

export function buildDraft(type, data, now = new Date()) {
  const { title, text } = templates[type].build(data, now);
  return { type, title, text: `${text}\n${DISCLAIMER}` };
}
